<table>
 <tr>
  <th>Idx</th>
  <th>Filename</th>
 </tr>
{queue_list}
 <tr>
  <td>{$item->queue_idx}</td>
  <td>{$item->queue_file_name}</td>
  <td>{$item->queue_file_hash}</td>
  <td>{$item->queue_state}</td>
  <td>{$item->queue_time}</td>
 </tr>
{/queue_list}
